### ISSUE TITLE
Not DnD5e 4/DnDe24 compatible.

### ISSUE THREAD

**Issue by SDoehren** [krbz999/alternative-exhaustion-5e#4]
The module loads and give the ability to add 10 levels of exhaustion but is not overriding the 5e24 rules of -2x to abilities, attacks, etc and reduced walk speed.

**Comment by krbz999** [comment]
I don't think maintaining this module is worth it with the '24 rules released. Those who want similar-ish rules can use the '24 rules, and otherwise there's a lot of added complexity to make this compatible with the newest version according to their various settings.

This was a small module intended to allow users to make use of the playtest exhaustion rules since those got scrapped, and since the system has plenty of support for similar rules now, I'm not gonna be able to justify the effort.

I will push an update to set the system maximum to v3.3.1.
